session Arbitrage = "HOL-Probability" +
  sessions
    Martingales
    Kolmogorov_Chentsov
  theories
    Stopped_Adaptedness
    Brownian_Stopped
    Brownian_Exit
    Random_Walk_Market
    Relative_Arbitrage_Comparison
    Brownian_Optimal_Boundary
    Relative_Arbitrage_Ito
    Stochastic_Integral
    Value_Function
    Envelopes
    Lemma_2_1_Exact
    Eigenvalues
    Eigenvalue_Continuity
    Threshold_Chain
    Lemma_3_1
    Poincare_Separation
