session Arbitrage = "HOL-Probability" +
  sessions
    Martingales
    Kolmogorov_Chentsov
    Levy_Prokhorov_Metric
    Standard_Borel_Spaces
    "HOL-Complex_Analysis"
  theories
    Stopped_Adaptedness
    Brownian_Stopped
    Brownian_Exit
    Random_Walk_Market
    Relative_Arbitrage_Comparison
    Brownian_Optimal_Boundary
    Relative_Arbitrage_Ito
    Stochastic_Integral
    Value_Function
    Envelopes
    Lemma_2_1_Exact
    Eigenvalues
    Eigenvalue_Continuity
    Threshold_Chain
    Lemma_3_1
    Poincare_Separation
    Lemma_3_1_Envelopes
    Section_2_Compactness
    Vitali_Convergence
    Measure_Continuity_Sets
    Sampled_Martingale
    Moment_Bounds
    Stacking_Intervals
    Sampled_Quadratic_Variation
    Ito_Covariation
    Stochastic_Integral_Simple
    L2_Limits
    Stochastic_Integral_L2
    Increment_Moments
    Increment_Tails
    Dyadic_Chaining
    Modulus_Tails
    Conditional_UI
    Stopped_Localization
    Holder_Interpolation
    Path_Space
    Path_Tightness
    Path_Tightness_Market
    Section_2_Usc
    Deterministic_Radius_Market
    Theorem_1_1
    Sup_Convolution
    Comparison_Assembly
