
(*<*)
theory Natural_Filtration
  imports "Martingales.Martingale"
begin

(*>*)

text \<open>
  Facts about @{const natural_filtration} and about a sub-\<open>\<sigma>\<close>-algebra's
  generator that the AFP's \<open>Martingales\<close> entry leaves to be reproved: pulling
  a natural filtration back along a pushforward, monotonicity and congruence
  of the natural filtration, and passing the vanishing of set integrals from
  a generating \<open>\<pi>\<close>-system to the whole generated \<open>\<sigma>\<close>-algebra.
\<close>

section \<open>Pulling a natural filtration back along a pushforward\<close>

text \<open>The \<open>pull\<close> hypothesis of \<open>martingale_distr\<close> in the case that matters here:
  the target filtration is the natural one of the coordinate process.  Then it
  is enough that each coordinate of the composed map is measurable at the right
  level --- the generator of a natural filtration is exactly the family of
  preimages of the coordinates.\<close>

lemma natural_filtration_pull:
  fixes Y :: "real \<Rightarrow> 'b \<Rightarrow> 'c :: {second_countable_topology, banach}"
  assumes into: "\<And>\<omega>. \<omega> \<in> space (FF u) \<Longrightarrow> \<phi> \<omega> \<in> space N"
    and comp: "\<And>v. 0 \<le> v \<Longrightarrow> v \<le> u \<Longrightarrow> (\<lambda>\<omega>. Y v (\<phi> \<omega>)) \<in> borel_measurable (FF u)"
  shows "\<phi> \<in> FF u \<rightarrow>\<^sub>M natural_filtration N (0::real) Y u"
proof (rule measurable_sigma_sets)
  show "sets (natural_filtration N 0 Y u)
      = sigma_sets (space N) (\<Union>v\<in>{0..u}. {Y v -` A \<inter> space N | A. A \<in> borel})"
    by (rule sets_natural_filtration)
  show "(\<Union>v\<in>{0..u}. {Y v -` A \<inter> space N | A. A \<in> borel}) \<subseteq> Pow (space N)" by blast
  show "\<phi> \<in> space (FF u) \<rightarrow> space N" using into by blast
  fix S assume "S \<in> (\<Union>v\<in>{0..u}. {Y v -` A \<inter> space N | A. A \<in> borel})"
  then obtain v A where v: "0 \<le> v" "v \<le> u" and A: "A \<in> sets borel"
    and S: "S = Y v -` A \<inter> space N" by auto
  have "\<phi> -` S \<inter> space (FF u) = (\<lambda>\<omega>. Y v (\<phi> \<omega>)) -` A \<inter> space (FF u)"
    unfolding S using into by auto
  also have "\<dots> \<in> sets (FF u)"
    using comp[OF v] A by (rule measurable_sets)
  finally show "\<phi> -` S \<inter> space (FF u) \<in> sets (FF u)" .
qed

text \<open>The evaluations of a natural filtration, in the two shapes the pushforward
  needs them.\<close>

lemma natural_filtration_eval:
  fixes Y :: "real \<Rightarrow> 'b \<Rightarrow> 'c :: {second_countable_topology, banach}"
  assumes v: "0 \<le> v" and vu: "v \<le> u"
  shows "Y v \<in> borel_measurable (natural_filtration N (0::real) Y u)"
  unfolding natural_filtration_def
  by (rule measurable_family_vimage_algebra) (use v vu in auto)

section \<open>Monotonicity and congruence of the natural filtration\<close>

lemma sets_natural_filtration_mono:
  fixes i j :: "'b :: {second_countable_topology, order_topology}"
  assumes ij: "i \<le> j"
  shows "sets (natural_filtration M t\<^sub>0 X i) \<subseteq> sets (natural_filtration M t\<^sub>0 X j)"
  unfolding sets_natural_filtration using ij by (intro sigma_sets_subseteq) force

lemma natural_filtration_cong_space:
  assumes "space M = space N"
  shows "natural_filtration M t\<^sub>0 X t = natural_filtration N t\<^sub>0 X t"
  unfolding natural_filtration_def using assms by simp

section \<open>A sub-\<open>\<sigma>\<close>-algebra generated by a \<open>\<pi>\<close>-system\<close>

lemma subalgebra_self: "subalgebra M M"
  by (simp add: subalgebra_def)

text \<open>A \<open>\<G>\<close>-measurable function all of whose \<open>\<G>\<close>-set integrals vanish is
  almost everywhere zero, for \<open>\<G>\<close> a sub-\<open>\<sigma>\<close>-algebra of \<open>M\<close>.\<close>

lemma AE_nonpos_of_set_integral_zero:
  fixes f :: "'a \<Rightarrow> real"
  assumes G: "subalgebra M G" and int: "integrable M f"
    and fm: "f \<in> borel_measurable G"
    and z: "\<And>A. A \<in> sets G \<Longrightarrow> set_lebesgue_integral M A f = 0"
  shows "AE \<omega> in M. f \<omega> \<le> 0"
proof -
  have spG: "space G = space M" using G by (simp add: subalgebra_def)
  let ?A = "{\<omega> \<in> space G. 0 < f \<omega>}"
  have A: "?A \<in> sets G" using fm by measurable
  have AM: "?A \<in> sets M" using A G by (auto simp: subalgebra_def)
  have ii: "integrable M (\<lambda>\<omega>. indicator ?A \<omega> *\<^sub>R f \<omega>)"
    by (rule integrable_mult_indicator[OF AM int])
  have inn: "AE \<omega> in M. 0 \<le> indicator ?A \<omega> *\<^sub>R f \<omega>"
    by (rule AE_I2) (auto simp: indicator_def)
  have zi: "(\<integral>\<omega>. indicator ?A \<omega> *\<^sub>R f \<omega> \<partial>M) = 0"
    using z[OF A] unfolding set_lebesgue_integral_def .
  have "AE \<omega> in M. indicator ?A \<omega> *\<^sub>R f \<omega> = 0"
    using ii inn zi by (simp add: integral_nonneg_eq_0_iff_AE)
  moreover have "AE \<omega> in M. \<omega> \<in> space M" by (rule AE_I2) simp
  ultimately show ?thesis
    by eventually_elim (auto simp: indicator_def spG split: if_split_asm)
qed

lemma AE_zero_of_set_integral_zero:
  fixes f :: "'a \<Rightarrow> real"
  assumes G: "subalgebra M G" and int: "integrable M f"
    and fm: "f \<in> borel_measurable G"
    and z: "\<And>A. A \<in> sets G \<Longrightarrow> set_lebesgue_integral M A f = 0"
  shows "AE \<omega> in M. f \<omega> = 0"
proof -
  have up: "AE \<omega> in M. f \<omega> \<le> 0"
    by (rule AE_nonpos_of_set_integral_zero[OF G int fm z])
  have zn: "set_lebesgue_integral M A (\<lambda>\<omega>. - f \<omega>) = 0" if A: "A \<in> sets G" for A
  proof -
    have AM: "A \<in> sets M" using A G by (auto simp: subalgebra_def)
    have "(\<integral>\<omega>. indicator A \<omega> *\<^sub>R (- f \<omega>) \<partial>M)
        = (\<integral>\<omega>. - (indicator A \<omega> *\<^sub>R f \<omega>) \<partial>M)" by simp
    also have "\<dots> = - (\<integral>\<omega>. indicator A \<omega> *\<^sub>R f \<omega> \<partial>M)"
      by (rule Bochner_Integration.integral_minus)
    also have "\<dots> = 0" using z[OF A] unfolding set_lebesgue_integral_def by simp
    finally show ?thesis unfolding set_lebesgue_integral_def .
  qed
  have dn: "AE \<omega> in M. - f \<omega> \<le> 0"
    by (rule AE_nonpos_of_set_integral_zero[OF G integrable_minus[OF int] _ zn])
       (use fm in simp)
  show ?thesis using up dn by eventually_elim simp
qed

text \<open>Passing the vanishing of set integrals from a generating \<open>\<pi>\<close>-system to
  the whole generated \<open>\<sigma>\<close>-algebra is a Dynkin argument:
  @{thm [source] sigma_sets_induct_disjoint} does the induction and
  @{thm [source] lebesgue_integral_countable_add} discharges its
  disjoint-union case.  The lemma is stated for a general measure and
  generating \<open>\<pi>\<close>-system.\<close>

lemma set_integral_zero_of_generator:
  fixes g :: "'a \<Rightarrow> real"
  assumes G: "subalgebra M G"
    and gi: "integrable M g"
    and Est: "Int_stable E"
    and Epow: "E \<subseteq> Pow (space M)"
    and Egen: "sets G = sigma_sets (space M) E"
    and Esp: "space M \<in> E"
    and z: "\<And>B. B \<in> E \<Longrightarrow> set_lebesgue_integral M B g = 0"
    and A: "A \<in> sets G"
  shows "set_lebesgue_integral M A g = 0"
proof -
  have GM: "sets G \<subseteq> sets M" using G by (simp add: subalgebra_def)
  have inM: "B \<in> sets M" if "B \<in> sigma_sets (space M) E" for B
    using that GM Egen by auto
  have si: "set_integrable M B g" if "B \<in> sets M" for B
    unfolding set_integrable_def by (rule integrable_mult_indicator[OF that gi])
  have Asig: "A \<in> sigma_sets (space M) E" using A Egen by simp
  from Est Epow Asig show ?thesis
  proof (induction rule: sigma_sets_induct_disjoint)
    case (basic B)
    then show ?case by (rule z)
  next
    case empty
    show ?case by (simp add: set_lebesgue_integral_def)
  next
    case (compl B)
    have BM: "B \<in> sets M" by (rule inM[OF compl.hyps])
    have CM: "space M - B \<in> sets M" using BM by (rule sets.compl_sets)
    have "set_lebesgue_integral M ((space M - B) \<union> B) g
        = set_lebesgue_integral M (space M - B) g
          + set_lebesgue_integral M B g"
      by (rule set_integral_Un[OF _ si[OF CM] si[OF BM]]) auto
    moreover have "(space M - B) \<union> B = space M"
      using sets.sets_into_space[OF BM] by auto
    ultimately have "set_lebesgue_integral M (space M) g
        = set_lebesgue_integral M (space M - B) g
          + set_lebesgue_integral M B g" by simp
    then show ?case using z[OF Esp] compl.IH by simp
  next
    case (union F)
    have FM: "F i \<in> sets M" for i using union.hyps(2) inM by blast
    have UM: "(\<Union>i. F i) \<in> sets M"
      by (rule sets.countable_nat_UN) (use FM in auto)
    have "set_lebesgue_integral M (\<Union>i. F i) g
        = (\<Sum>i. set_lebesgue_integral M (F i) g)"
      by (rule lebesgue_integral_countable_add[OF FM _ si[OF UM]])
         (use union.hyps(1) in \<open>auto simp: disjoint_family_on_def\<close>)
    also have "\<dots> = 0" using union.IH by simp
    finally show ?case .
  qed
qed

section \<open>A probability-one event contains almost every point\<close>

text \<open>The bridge from the library's real-valued
  @{thm [source] prob_space.AE_prob_1} through
  @{thm [source] finite_measure.emeasure_eq_measure}.\<close>

lemma AE_mem_of_emeasure_1:
  assumes PS: "prob_space M" and one: "emeasure M C = 1"
  shows "AE w in M. w \<in> C"
proof -
  interpret PM: prob_space M by (rule PS)
  have "measure M C = 1" using one by (simp add: PM.emeasure_eq_measure)
  then show ?thesis by (rule PM.AE_prob_1)
qed

(*<*)
end
(*>*)
