section \<open>The path space on the half-line\<close>

(*<*)
theory Path_Space_Infinite
  imports Path_Space
begin
(*>*)

text \<open>Continuous paths on \<open>{0..}\<close>, as a measurable space generated by the
  evaluations.  Weak convergence is never taken on this space -- the results
  that need it are proved on the compact horizons of
  @{theory Continuous_Path_Spaces.Path_Space} and transported -- so no metric is
  put on it, and the construction costs only the generator and the two
  measurability facts below.\<close>

definition ipath :: "(real \<Rightarrow> 'b::polish_space) set" where
  "ipath = {f. f = restrict f {0..} \<and> continuous_on {0..} f}"

definition ipath_gen :: "((real \<Rightarrow> 'b::polish_space) set) set" where
  "ipath_gen =
     {S. \<exists>t A. 0 \<le> t \<and> open A \<and> S = {f \<in> ipath. f t \<in> A}}"

definition ipath_space :: "(real \<Rightarrow> 'b::polish_space) measure" where
  "ipath_space = sigma ipath ipath_gen"

lemma ipath_gen_subset: "ipath_gen \<subseteq> Pow (ipath :: (real \<Rightarrow> 'b::polish_space) set)"
  unfolding ipath_gen_def by blast

lemma space_ipath_space[simp]:
  "space (ipath_space :: (real \<Rightarrow> 'b::polish_space) measure) = ipath"
  unfolding ipath_space_def by (rule space_measure_of[OF ipath_gen_subset])

lemma sets_ipath_space:
  "sets (ipath_space :: (real \<Rightarrow> 'b::polish_space) measure) = sigma_sets ipath ipath_gen"
  unfolding ipath_space_def by (rule sets_measure_of[OF ipath_gen_subset])

lemma ipathI:
  assumes "f = restrict f {0..}" and "continuous_on {0..} f"
  shows "f \<in> ipath"
  using assms unfolding ipath_def by blast

lemma ipath_continuous_on:
  assumes "f \<in> (ipath :: (real \<Rightarrow> 'b::polish_space) set)" and "S \<subseteq> {0..}"
  shows "continuous_on S f"
  using assms unfolding ipath_def by (blast intro: continuous_on_subset)

text \<open>The evaluations are measurable, which is the defining property of the
  generator.\<close>

lemma ipath_eval_measurable:
  assumes t: "0 \<le> t"
  shows "(\<lambda>f. f t) \<in> borel_measurable (ipath_space :: (real \<Rightarrow> 'b::polish_space) measure)"
proof (rule borel_measurableI)
  fix S :: "'b set"
  assume S: "open S"
  have "(\<lambda>f. f t) -` S \<inter> space ipath_space = {f \<in> ipath. f t \<in> S}"
    by auto
  moreover have "{f \<in> ipath. f t \<in> S} \<in> ipath_gen"
    unfolding ipath_gen_def using t S by blast
  ultimately show "(\<lambda>f. f t) -` S \<inter> space ipath_space \<in> sets ipath_space"
    unfolding sets_ipath_space by (metis sigma_sets.Basic)
qed

text \<open>Restricting a path to a compact horizon lands in the space of
  @{theory Continuous_Path_Spaces.Path_Space} and is measurable.\<close>

lemma restrict_ipath_mspace:
  assumes T: "0 \<le> T" and f: "f \<in> (ipath :: (real \<Rightarrow> 'b::polish_space) set)"
  shows "restrict f {0..T} \<in> mspace (path_metric T :: (real \<Rightarrow> 'b) metric)"
proof (rule mspace_path_metricI)
  show "continuous_on {0..T} f"
    by (rule ipath_continuous_on[OF f]) (simp add: T)
qed

theorem restrict_ipath_measurable:
  assumes T: "0 \<le> T"
  shows "(\<lambda>f. restrict f {0..T})
      \<in> (ipath_space :: (real \<Rightarrow> 'b::polish_space) measure)
        \<rightarrow>\<^sub>M (path_borel T :: (real \<Rightarrow> 'b) measure)"
proof (rule pathify_measurable[OF T])
  fix t :: real assume "t \<in> {0..T}"
  then show "(\<lambda>f. f t) \<in> borel_measurable (ipath_space :: (real \<Rightarrow> 'b) measure)"
    by (intro ipath_eval_measurable) simp
next
  fix f :: "real \<Rightarrow> 'b"
  assume "f \<in> space (ipath_space :: (real \<Rightarrow> 'b) measure)"
  then have "f \<in> ipath" by simp
  then show "continuous_on {0..T} (\<lambda>t. f t)"
    by (rule ipath_continuous_on) (simp add: T)
qed

text \<open>The law of a process with continuous paths on the half-line, and its
  restriction to a compact horizon, which is the corresponding
  @{const path_law}.\<close>

definition ipath_law ::
  "'a measure \<Rightarrow> (real \<Rightarrow> 'a \<Rightarrow> 'b::polish_space) \<Rightarrow> (real \<Rightarrow> 'b) measure"
  where "ipath_law M X = distr M ipath_space (\<lambda>\<omega>. restrict (\<lambda>t. X t \<omega>) {0..})"

lemma sets_ipath_law[simp]:
  "sets (ipath_law M X :: (real \<Rightarrow> 'b::polish_space) measure) = sets ipath_space"
  unfolding ipath_law_def by simp

lemma ipathify_measurable:
  fixes X :: "real \<Rightarrow> 'a \<Rightarrow> 'b::polish_space"
  assumes Xm: "\<And>t. 0 \<le> t \<Longrightarrow> X t \<in> borel_measurable M"
    and cont: "\<And>\<omega>. \<omega> \<in> space M \<Longrightarrow> continuous_on {0..} (\<lambda>t. X t \<omega>)"
  shows "(\<lambda>\<omega>. restrict (\<lambda>t. X t \<omega>) {0..}) \<in> M \<rightarrow>\<^sub>M ipath_space"
  unfolding ipath_space_def
proof (rule measurable_measure_of[OF ipath_gen_subset])
  show "(\<lambda>\<omega>. restrict (\<lambda>t. X t \<omega>) {0..}) \<in> space M \<rightarrow> ipath"
  proof
    fix \<omega> assume w: "\<omega> \<in> space M"
    show "restrict (\<lambda>t. X t \<omega>) {0..} \<in> ipath"
    proof (rule ipathI)
      show "restrict (\<lambda>t. X t \<omega>) {0..} = restrict (restrict (\<lambda>t. X t \<omega>) {0..}) {0..}"
        by simp
      have "continuous_on {0..} (\<lambda>t. X t \<omega>)
          = continuous_on {0..} (restrict (\<lambda>t. X t \<omega>) {0..})"
        by (rule continuous_on_cong) auto
      then show "continuous_on {0..} (restrict (\<lambda>t. X t \<omega>) {0..})"
        using cont[OF w] by simp
    qed
  qed
next
  fix S :: "(real \<Rightarrow> 'b) set"
  assume "S \<in> ipath_gen"
  then obtain t A where t: "0 \<le> t" and A: "open A"
    and S: "S = {f \<in> ipath. f t \<in> A}" unfolding ipath_gen_def by blast
  have inI: "restrict (\<lambda>u. X u \<omega>) {0..} \<in> ipath" if "\<omega> \<in> space M" for \<omega>
  proof (rule ipathI)
    show "restrict (\<lambda>u. X u \<omega>) {0..} = restrict (restrict (\<lambda>u. X u \<omega>) {0..}) {0..}"
      by simp
    have "continuous_on {0..} (\<lambda>u. X u \<omega>)
        = continuous_on {0..} (restrict (\<lambda>u. X u \<omega>) {0..})"
      by (rule continuous_on_cong) auto
    then show "continuous_on {0..} (restrict (\<lambda>u. X u \<omega>) {0..})"
      using cont[OF that] by simp
  qed
  have "(\<lambda>\<omega>. restrict (\<lambda>t. X t \<omega>) {0..}) -` S \<inter> space M
      = (X t) -` A \<inter> space M"
    unfolding S using t inI by auto
  moreover have "(X t) -` A \<inter> space M \<in> sets M"
    using Xm[OF t] A by (simp add: borel_measurable_vimage_open)
  ultimately show "(\<lambda>\<omega>. restrict (\<lambda>t. X t \<omega>) {0..}) -` S \<inter> space M \<in> sets M"
    by simp
qed

(*<*)
end
(*>*)
