section \<open>The class and the value function on the half-line\<close>

(*<*)
theory Exit_Class_Infinite
  imports Dynamic_Programming_Assembly "Continuous_Path_Spaces.Path_Space_Infinite"
    "Continuous_Time_Martingales.Essential_Infimum"
    "Continuous_Path_Spaces.Path_Exit_Times"
    Path_Law_Sampling
begin
(*>*)

text \<open>Eq. (1.6)--(1.7) of \<^cite>\<open>LaiShkolnikovSoner\<close> without the horizon cap: the class
  is a set of laws on the paths of @{theory Continuous_Path_Spaces.Path_Space_Infinite},
  the covariation constraint is required at every pair of times, and the
  martingale clauses carry no stopping.  The capped development is reached
  through the restriction of a law to a compact horizon.\<close>

subsection \<open>The uncapped exit time\<close>










definition iexit_class ::
  "nat \<Rightarrow> real \<Rightarrow> real^'n::finite \<Rightarrow> (('n pairpath) measure) set"
  where
  "iexit_class k L x = {P.
     prob_space P \<and>
     sets P = sets (ipath_space :: ('n pairpath) measure) \<and>
     (AE \<omega> in P. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0) \<and>
     (AE \<omega> in P. \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow>
        (1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L) \<and>
     martingale P (natural_filtration P 0 (\<lambda>t \<omega>. \<omega> t)) 0
       (\<lambda>t \<omega>. fst (\<omega> t)) \<and>
     martingale P (natural_filtration P 0 (\<lambda>t \<omega>. \<omega> t)) 0
       (\<lambda>t \<omega>. outerp (fst (\<omega> t)) - snd (\<omega> t))}"

definition iexit_val ::
  "nat \<Rightarrow> real \<Rightarrow> (real^'n::finite) set \<Rightarrow> real^'n \<Rightarrow> ennreal"
  where
  "iexit_val k L K x =
     Sup ((\<lambda>Q. ess_inf Q (\<lambda>\<omega>. iexit K (\<lambda>t. fst (\<omega> t)))) ` iexit_class k L x)"

lemma iexit_class_prob:
  "P \<in> iexit_class k L x \<Longrightarrow> prob_space P"
  unfolding iexit_class_def by blast

lemma iexit_class_sets:
  "P \<in> iexit_class k L x \<Longrightarrow> sets P = sets (ipath_space :: ('n::finite pairpath) measure)"
  unfolding iexit_class_def by blast

lemma iexit_class_start:
  "P \<in> iexit_class k L x \<Longrightarrow> AE \<omega> in P. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0"
  unfolding iexit_class_def by blast

subsection \<open>Restriction to a compact horizon\<close>

text \<open>The cut of a law on the half-line is a law on the horizon-\<open>S\<close> path
  space.  @{thm [source] pcut_adapted} needs nothing of the underlying space,
  so the adaptedness of the cut coordinates carries over unchanged.\<close>


lemma iexit_class_diffquot:
  "P \<in> iexit_class k L x \<Longrightarrow>
     AE \<omega> in P. \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow>
       (1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L"
  unfolding iexit_class_def by blast

lemma iexit_class_X_martingale:
  "P \<in> iexit_class k L x \<Longrightarrow>
     martingale P (natural_filtration P 0 (\<lambda>t \<omega>. \<omega> t)) 0
       (\<lambda>t \<omega>. fst (\<omega> t) :: real^'n::finite)"
  unfolding iexit_class_def by blast

lemma iexit_class_comp_martingale:
  "P \<in> iexit_class k L x \<Longrightarrow>
     martingale P (natural_filtration P 0 (\<lambda>t \<omega>. \<omega> t)) 0
       (\<lambda>t \<omega>. outerp (fst (\<omega> t) :: real^'n::finite) - snd (\<omega> t))"
  unfolding iexit_class_def by blast

text \<open>The class is a set of laws of the pair \<open>(X, \<langle>X\<rangle>)\<close>, and the martingale
  clauses above are stated for the natural filtration of that pair, which is a
  priori larger than the natural filtration of \<open>X\<close>.  The paper's own filtration
  is the one generated by the coordinate process \<open>X\<close>; the martingale property
  transfers to it by the tower property, so a member of the class does have \<open>X\<close>
  a martingale in the paper's sense, via \<open>martingale_coarser_filtration\<close> from
  @{theory Continuous_Time_Martingales.Martingale_Algebra}.\<close>

text \<open>The cut of a member of the uncapped class is a member of the capped one.
  Every clause transfers along @{const pcut}; the covariation and martingale
  clauses are simpler here than in @{thm [source] exit_class_pcut}, since the
  uncapped class constrains every pair of times and stops nothing.\<close>

theorem iexit_class_pcut:
  fixes P :: "('n::finite pairpath) measure"
  assumes S: "0 \<le> S" and P: "P \<in> iexit_class k L x"
  shows "pair_law_of S (pcut S) P \<in> exit_class k L S x"
proof -
  let ?Q = "pair_law_of S (pcut S) P"
  let ?B = "(path_borel S :: ('n pairpath) measure)"
  let ?F = "natural_filtration P 0 (\<lambda>v \<omega> :: 'n pairpath. \<omega> v)"
  let ?G = "natural_filtration ?Q 0 (\<lambda>v \<omega> :: 'n pairpath. \<omega> v)"
  interpret P: prob_space P by (rule iexit_class_prob[OF P])
  have phim: "pcut S \<in> P \<rightarrow>\<^sub>M ?B"
    by (rule ipcut_measurable[OF S iexit_class_sets[OF P]])
  have prob': "prob_space ?Q"
    unfolding pair_law_of_def by (rule P.prob_space_distr[OF phim])
  have adap: "(\<lambda>\<omega> :: 'n pairpath. pcut S \<omega> r) \<in> borel_measurable (?F u)"
    if "0 \<le> r" "r \<le> u" for r u
    by (rule pcut_adapted[OF S that])

  \<comment> \<open>clause (i): the initial condition\<close>
  have start': "AE \<omega> in ?Q. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0"
  proof -
    have ev: "(\<lambda>\<omega> :: 'n pairpath. \<omega> 0) \<in> borel_measurable ?B"
      by (rule pair_law_eval_measurable[OF refl])
    have mset: "{\<omega> \<in> space ?B. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0} \<in> sets ?B"
    proof -
      have "{\<omega> \<in> space ?B. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0}
          = (\<lambda>\<omega> :: 'n pairpath. \<omega> 0) -` {(x, 0)} \<inter> space ?B"
        by (auto simp: prod_eq_iff)
      then show ?thesis using measurable_sets[OF ev] by simp
    qed
    have iff: "(AE \<omega> in ?Q. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0)
        = (AE \<omega> in P. fst (pcut S \<omega> 0) = x \<and> snd (pcut S \<omega> 0) = 0)"
      unfolding pair_law_of_def by (rule AE_distr_iff[OF phim mset])
    have z: "(0::real) \<in> {0..S}" using S by simp
    have "AE \<omega> in P. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0"
      by (rule iexit_class_start[OF P])
    then have "AE \<omega> in P. fst (pcut S \<omega> 0) = x \<and> snd (pcut S \<omega> 0) = 0"
      by eventually_elim (simp add: pcut_apply[OF z])
    then show ?thesis unfolding iff .
  qed

  \<comment> \<open>clause (ii): the covariation constraint\<close>
  have cov': "AE \<omega> in ?Q. \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow> t \<le> S \<longrightarrow>
      (1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L"
  proof (rule exit_class_diffquot_of_pairs[OF sets_pair_law_of])
    fix p q :: real
    assume pq: "p \<in> {0..S}" "q \<in> {0..S}" "p < q"
    have mm: "{\<omega> \<in> space ?B.
        (1 / (q - p)) *\<^sub>R (snd (\<omega> q) - snd (\<omega> p)) \<in> sconstraint k L} \<in> sets ?B"
      using borel_of_closed[OF closedin_diffquot_constraint[OF pq(1) pq(2)]]
      by (simp add: space_borel_of)
    have iff: "(AE \<omega> in ?Q.
          (1 / (q - p)) *\<^sub>R (snd (\<omega> q) - snd (\<omega> p)) \<in> sconstraint k L)
        = (AE \<omega> in P. (1 / (q - p))
            *\<^sub>R (snd (pcut S \<omega> q) - snd (pcut S \<omega> p)) \<in> sconstraint k L)"
      unfolding pair_law_of_def by (rule AE_distr_iff[OF phim mm])
    have "AE \<omega> in P. \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow>
        (1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L"
      by (rule iexit_class_diffquot[OF P])
    then have "AE \<omega> in P. (1 / (q - p))
        *\<^sub>R (snd (pcut S \<omega> q) - snd (pcut S \<omega> p)) \<in> sconstraint k L"
    proof eventually_elim
      case (elim \<omega>)
      have "(1 / (q - p)) *\<^sub>R (snd (\<omega> q) - snd (\<omega> p)) \<in> sconstraint k L"
        using elim pq by auto
      then show ?case using pq by (simp add: pcut_apply)
    qed
    then show "AE \<omega> in ?Q.
        (1 / (q - p)) *\<^sub>R (snd (\<omega> q) - snd (\<omega> p)) \<in> sconstraint k L"
      unfolding iff .
  qed

  \<comment> \<open>clause (iii): \<open>X\<close> is a martingale\<close>
  have mgX': "martingale ?Q ?G 0 (\<lambda>u \<omega>. fst (\<omega> (min u S)) :: real^'n)"
  proof (rule martingale_pair_law[OF P.prob_space_axioms phim adap])
    fix u :: real assume u: "0 \<le> u"
    have fstB: "(fst :: (real^'n) \<times> (real^'n^'n) \<Rightarrow> real^'n)
        \<in> borel_measurable borel"
      by (intro borel_measurable_continuous_onI continuous_intros)
    have ev: "(\<lambda>\<omega> :: 'n pairpath. \<omega> (min u S)) \<in> ?G u \<rightarrow>\<^sub>M borel"
      unfolding natural_filtration_def
      by (rule measurable_family_vimage_algebra) (use u S in auto)
    show "(\<lambda>\<omega> :: 'n pairpath. fst (\<omega> (min u S))) \<in> borel_measurable (?G u)"
      by (rule measurable_compose[OF ev fstB])
  next
    show "martingale P ?F 0 (\<lambda>u \<omega>. fst (pcut S \<omega> (min u S)) :: real^'n)"
    proof (rule martingale_cong_ge
        [OF martingale_stopped_const[OF S iexit_class_X_martingale[OF P]]])
      fix u :: real assume u: "0 \<le> u"
      have mI: "min u S \<in> {0..S}" using u S by simp
      show "(\<lambda>\<omega> :: 'n pairpath. fst (\<omega> (min u S)))
          = (\<lambda>\<omega>. fst (pcut S \<omega> (min u S)) :: real^'n)"
        by (rule ext) (simp add: pcut_apply[OF mI])
    qed
  qed

  \<comment> \<open>clause (iv): the compensated process is a martingale\<close>
  have mgC': "martingale ?Q ?G 0
      (\<lambda>u \<omega>. outerp (fst (\<omega> (min u S)) :: real^'n) - snd (\<omega> (min u S)))"
  proof (rule martingale_pair_law[OF P.prob_space_axioms phim adap])
    fix u :: real assume u: "0 \<le> u"
    have e: "(\<lambda>p :: (real^'n) \<times> (real^'n^'n). outerp (fst p) - snd p)
        = (\<lambda>p. \<chi> i j. fst p $ i * fst p $ j - snd p $ i $ j)"
      by (rule ext) (simp add: outerp_def vec_eq_iff)
    have cB: "(\<lambda>p :: (real^'n) \<times> (real^'n^'n). outerp (fst p) - snd p)
        \<in> borel_measurable borel"
      unfolding e
      by (intro borel_measurable_continuous_onI continuous_on_vec_lambda
          continuous_intros)
    have ev: "(\<lambda>\<omega> :: 'n pairpath. \<omega> (min u S)) \<in> ?G u \<rightarrow>\<^sub>M borel"
      unfolding natural_filtration_def
      by (rule measurable_family_vimage_algebra) (use u S in auto)
    show "(\<lambda>\<omega> :: 'n pairpath. outerp (fst (\<omega> (min u S))) - snd (\<omega> (min u S)))
        \<in> borel_measurable (?G u)"
      by (rule measurable_compose[OF ev cB])
  next
    show "martingale P ?F 0 (\<lambda>u \<omega>. outerp (fst (pcut S \<omega> (min u S)) :: real^'n)
        - snd (pcut S \<omega> (min u S)))"
    proof (rule martingale_cong_ge[OF martingale_stopped_const
          [OF S iexit_class_comp_martingale[OF P]]])
      fix u :: real assume u: "0 \<le> u"
      have mI: "min u S \<in> {0..S}" using u S by simp
      show "(\<lambda>\<omega> :: 'n pairpath. outerp (fst (\<omega> (min u S))) - snd (\<omega> (min u S)))
          = (\<lambda>\<omega>. outerp (fst (pcut S \<omega> (min u S)) :: real^'n)
              - snd (pcut S \<omega> (min u S)))"
        by (rule ext) (simp add: pcut_apply[OF mI])
    qed
  qed

  show ?thesis
    unfolding exit_class_def mem_Collect_eq
    using prob' sets_pair_law_of start' cov' mgX' mgC' by blast
qed

subsection \<open>The capped value dominates the capped uncapped value\<close>

text \<open>Restricting a member of the uncapped class to \<open>[0,T]\<close> gives a competitor
  for @{const exit_val} whose exit time is the uncapped one capped at \<open>T\<close>.
  Hence \<open>min (v, T) \<le> v\<^sub>T\<close>, one half of the identification of the two value
  functions.\<close>

theorem iexit_val_cap_le:
  fixes K :: "(real^'n::finite) set"
  assumes T: "0 \<le> T" and Kc: "closed K"
  shows "min (iexit_val k L K x) (ennreal T) \<le> exit_val k L T K x"
proof -
  have step: "min (ess_inf P (\<lambda>\<omega>. iexit K (\<lambda>t. fst (\<omega> t)))) (ennreal T)
      \<le> exit_val k L T K x"
    if P: "P \<in> iexit_class k L x" for P :: "('n pairpath) measure"
  proof -
    let ?Q = "pair_law_of T (pcut T) P"
    let ?B = "(path_borel T :: ('n pairpath) measure)"
    have Q: "?Q \<in> exit_class k L T x" by (rule iexit_class_pcut[OF T P])
    have phim: "pcut T \<in> P \<rightarrow>\<^sub>M ?B"
      by (rule ipcut_measurable[OF T iexit_class_sets[OF P]])
    have taum: "(\<lambda>\<omega> :: 'n pairpath. pexit T K (\<lambda>t. fst (\<omega> t)))
        \<in> borel_measurable ?B"
      by (rule pexit_path_measurable[OF T Kc refl])
    have "ess_inf_time ?Q (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (\<omega> t)))
        = ess_inf_time P (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (pcut T \<omega> t)))"
      unfolding pair_law_of_def
    proof (rule ess_inf_time_distr[OF phim])
      fix c :: ennreal
      show "{\<omega> \<in> space ?B. c \<le> ennreal (pexit T K (\<lambda>t. fst (\<omega> t)))} \<in> sets ?B"
        using taum by measurable
    qed
    also have "\<dots> = ess_inf_time P (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (\<omega> t)))"
      by (simp add: pexit_pcut)
    also have "\<dots> = ess_inf P (\<lambda>\<omega>. ennreal (pexit T K (\<lambda>t. fst (\<omega> t))))"
      by (rule ess_inf_ennreal[symmetric])
    also have "\<dots> = ess_inf P
        (\<lambda>\<omega>. min (iexit K (\<lambda>t. fst (\<omega> t))) (ennreal T))"
      by (simp add: iexit_cap[OF T])
    finally have eq: "ess_inf_time ?Q (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (\<omega> t)))
        = ess_inf P (\<lambda>\<omega>. min (iexit K (\<lambda>t. fst (\<omega> t))) (ennreal T))" .
    have "min (ess_inf P (\<lambda>\<omega>. iexit K (\<lambda>t. fst (\<omega> t)))) (ennreal T)
        \<le> ess_inf P (\<lambda>\<omega>. min (iexit K (\<lambda>t. fst (\<omega> t))) (ennreal T))"
      by (rule ess_inf_min_const)
    also have "\<dots> = ess_inf_time ?Q (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (\<omega> t)))"
      using eq by simp
    also have "\<dots> \<le> exit_val k L T K x"
      unfolding exit_val_def using Q by (intro Sup_upper) blast
    finally show ?thesis .
  qed
  show ?thesis
  proof (cases "ennreal T \<le> exit_val k L T K x")
    case True
    then show ?thesis using min.cobounded2 order_trans by blast
  next
    case False
    then have lt: "exit_val k L T K x < ennreal T" by simp
    have "iexit_val k L K x \<le> exit_val k L T K x"
      unfolding iexit_val_def
    proof (rule Sup_least)
      fix v assume "v \<in> (\<lambda>Q. ess_inf Q (\<lambda>\<omega>. iexit K (\<lambda>t. fst (\<omega> t))))
          ` iexit_class k L x"
      then obtain P :: "('n pairpath) measure"
        where P: "P \<in> iexit_class k L x"
          and v: "v = ess_inf P (\<lambda>\<omega>. iexit K (\<lambda>t. fst (\<omega> t)))" by blast
      have "min v (ennreal T) \<le> exit_val k L T K x" using step[OF P] v by simp
      then show "v \<le> exit_val k L T K x"
        using lt by (simp add: min_def split: if_splits)
    qed
    then show ?thesis using min.cobounded1 order_trans by blast
  qed
qed

subsection \<open>The converse, from an extension of a capped law\<close>

text \<open>The other half reduces to a single construction: every member of the
  horizon-\<open>T\<close> class is the cut of a member of the uncapped class.  Given that,
  the uncapped exit time dominates the capped one on the extension, and the
  inequality follows.  The construction itself is an iterated application of
  @{thm [source] exit_class_pglue_law}, whose continuation may be taken with
  covariation the identity by @{thm [source] mat_1_in_sconstraint}.\<close>

theorem iexit_val_ge_of_extension:
  fixes K :: "(real^'n::finite) set"
  assumes T: "0 \<le> T" and Kc: "closed K"
    and ext: "\<And>Q :: ('n pairpath) measure. Q \<in> exit_class k L T x \<Longrightarrow>
      \<exists>P \<in> iexit_class k L x. pair_law_of T (pcut T) P = Q"
  shows "exit_val k L T K x \<le> iexit_val k L K x"
  unfolding exit_val_def
proof (rule Sup_least)
  fix w assume "w \<in> (\<lambda>Q. ess_inf_time Q (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (\<omega> t))))
      ` exit_class k L T x"
  then obtain Q :: "('n pairpath) measure"
    where Q: "Q \<in> exit_class k L T x"
      and w: "w = ess_inf_time Q (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (\<omega> t)))" by blast
  obtain P :: "('n pairpath) measure"
    where P: "P \<in> iexit_class k L x" and cut: "pair_law_of T (pcut T) P = Q"
    using ext[OF Q] by blast
  let ?B = "(path_borel T :: ('n pairpath) measure)"
  have phim: "pcut T \<in> P \<rightarrow>\<^sub>M ?B"
    by (rule ipcut_measurable[OF T iexit_class_sets[OF P]])
  have taum: "(\<lambda>\<omega> :: 'n pairpath. pexit T K (\<lambda>t. fst (\<omega> t)))
      \<in> borel_measurable ?B"
    by (rule pexit_path_measurable[OF T Kc refl])
  have "w = ess_inf_time P (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (pcut T \<omega> t)))"
    unfolding w cut[symmetric] pair_law_of_def
  proof (rule ess_inf_time_distr[OF phim])
    fix c :: ennreal
    show "{\<omega> \<in> space ?B. c \<le> ennreal (pexit T K (\<lambda>t. fst (\<omega> t)))} \<in> sets ?B"
      using taum by measurable
  qed
  also have "\<dots> = ess_inf_time P (\<lambda>\<omega>. pexit T K (\<lambda>t. fst (\<omega> t)))"
    by (simp add: pexit_pcut)
  also have "\<dots> = ess_inf P (\<lambda>\<omega>. ennreal (pexit T K (\<lambda>t. fst (\<omega> t))))"
    by (rule ess_inf_ennreal[symmetric])
  also have "\<dots> \<le> ess_inf P (\<lambda>\<omega>. iexit K (\<lambda>t. fst (\<omega> t)))"
    by (rule ess_inf_mono) (simp add: pexit_le_iexit[OF T])
  also have "\<dots> \<le> iexit_val k L K x"
    unfolding iexit_val_def using P by (intro Sup_upper) blast
  finally show "w \<le> iexit_val k L K x" .
qed

subsection \<open>The two value functions agree once the horizon does not bind\<close>

text \<open>The hypothesis \<open>exit_val k L T K x < ennreal T\<close> is what the a priori
  bound \<open>exit_val_le_ball_bound\<close> supplies for a bounded \<open>K\<close> and a horizon
  above \<open>rK\<^sup>2 / (n - k)\<close>: the capped value is then strictly below the cap.  With both halves, the two value functions coincide, and every
  statement about @{const exit_val} is a statement about the value function of
  Eq. (1.6) as the paper writes it.\<close>

theorem iexit_val_eq_of_extension:
  fixes K :: "(real^'n::finite) set"
  assumes T: "0 \<le> T" and Kc: "closed K"
    and nobind: "exit_val k L T K x < ennreal T"
    and ext: "\<And>Q :: ('n pairpath) measure. Q \<in> exit_class k L T x \<Longrightarrow>
      \<exists>P \<in> iexit_class k L x. pair_law_of T (pcut T) P = Q"
  shows "iexit_val k L K x = exit_val k L T K x"
proof (rule antisym)
  have le: "min (iexit_val k L K x) (ennreal T) \<le> exit_val k L T K x"
    by (rule iexit_val_cap_le[OF T Kc])
  show "iexit_val k L K x \<le> exit_val k L T K x"
    using le nobind by (simp add: min_def split: if_splits)
next
  show "exit_val k L T K x \<le> iexit_val k L K x"
    by (rule iexit_val_ge_of_extension[OF T Kc ext])
qed

subsection \<open>Towards the extension: cutting a glue back\<close>

text \<open>Gluing a continuation onto a path at \<open>r\<close> and cutting back at \<open>r\<close>
  returns the original path, so an extension built by
  @{thm [source] exit_class_pglue_law} restricts to the law it extends.
  \<open>pcut_pglue\<close> lives in @{theory Relative_Arbitrage.Dynamic_Programming_Kernels}.\<close>

text \<open>Members of the horizon-\<open>r\<close> path space are extensional on \<open>{0..r}\<close>, so
  cutting there is the identity on them.  This is what turns
  @{thm [source] pcut_pglue} into the statement that the extension of a law
  restricts to that law.\<close>





definition ibmpair :: "('n::finite \<Rightarrow> real \<Rightarrow> real) \<Rightarrow> 'n pairpath"
  where "ibmpair \<omega> = restrict (\<lambda>t. (cbmX 0 t \<omega>, t *\<^sub>R mat 1)) {0..}"

lemma pcut_ibmpair: "pcut S (ibmpair \<omega>) = bmpair S \<omega>"
  by (rule ext) (auto simp: pcut_def ibmpair_def bmpair_def)

lemma ibmpair_measurable:
  "(ibmpair :: ('n::finite \<Rightarrow> real \<Rightarrow> real) \<Rightarrow> 'n pairpath)
      \<in> bm_paths \<rightarrow>\<^sub>M ipath_space"
proof -
  have "(\<lambda>\<omega> :: 'n \<Rightarrow> real \<Rightarrow> real. restrict
          (\<lambda>t. (cbmX (0 :: real^'n) t \<omega>, t *\<^sub>R (mat 1 :: real^'n^'n))) {0..})
      \<in> bm_paths \<rightarrow>\<^sub>M ipath_space"
  proof (rule ipathify_measurable)
    fix t :: real assume "0 \<le> t"
    have c: "(\<lambda>v :: real^'n. (v, t *\<^sub>R (mat 1 :: real^'n^'n)))
        \<in> borel_measurable borel"
      by (intro borel_measurable_continuous_onI continuous_intros)
    show "(\<lambda>\<omega> :: 'n \<Rightarrow> real \<Rightarrow> real.
          (cbmX (0 :: real^'n) t \<omega>, t *\<^sub>R (mat 1 :: real^'n^'n)))
        \<in> borel_measurable (bm_paths :: ('n \<Rightarrow> real \<Rightarrow> real) measure)"
      by (rule measurable_compose[OF measurable_cbmX c])
  next
    fix \<omega> :: "'n \<Rightarrow> real \<Rightarrow> real"
    show "continuous_on {0..}
        (\<lambda>t. (cbmX (0 :: real^'n) t \<omega>, t *\<^sub>R (mat 1 :: real^'n^'n)))"
      by (intro continuous_on_Pair cbmX_cont
          linear_continuous_on[OF bounded_linear_scaleR_left])
  qed
  then show ?thesis unfolding ibmpair_def by simp
qed

definition ibm_law :: "('n::finite pairpath) measure"
  where "ibm_law = distr bm_paths ipath_space ibmpair"

lemma sets_ibm_law[simp]:
  "sets (ibm_law :: ('n::finite pairpath) measure) = sets ipath_space"
  unfolding ibm_law_def by simp

lemma prob_space_ibm_law: "prob_space (ibm_law :: ('n::finite pairpath) measure)"
  unfolding ibm_law_def
  by (rule BMP.prob_space_distr[OF ibmpair_measurable])

lemma pair_law_of_pcut_ibm_law:
  assumes S: "0 \<le> S"
  shows "pair_law_of S (pcut S) (ibm_law :: ('n::finite pairpath) measure)
      = pair_law_of S (bmpair S) bm_paths"
proof -
  have "pair_law_of S (pcut S) (ibm_law :: ('n pairpath) measure)
      = distr bm_paths (path_borel S :: ('n pairpath) measure) (pcut S \<circ> ibmpair)"
    unfolding ibm_law_def pair_law_of_def
    by (rule distr_distr[OF ipcut_measurable[OF S refl] ibmpair_measurable])
  also have "\<dots> = pair_law_of S (bmpair S) bm_paths"
    unfolding pair_law_of_def by (simp add: comp_def pcut_ibmpair)
  finally show ?thesis .
qed

theorem ibm_law_cut_in_class:
  assumes S: "0 \<le> S" and L: "1 \<le> L"
  shows "pair_law_of S (pcut S) (ibm_law :: ('n::finite pairpath) measure)
      \<in> exit_class k L S (0 :: real^'n)"
  unfolding pair_law_of_pcut_ibm_law[OF S]
  by (rule bmpair_law_in_paper_pair_class[OF S L])

subsection \<open>The extension of a horizon law to the half-line\<close>

text \<open>Only the values of the continuation on \<open>{0..S-r}\<close> reach the glue, and
  at the glue point itself the glue is the cut of the law it extends.\<close>




definition iextend ::
  "real \<Rightarrow> ('n::finite pairpath) measure \<Rightarrow> ('n pairpath) measure"
  where "iextend T Q =
     distr (Q \<Otimes>\<^sub>M ibm_law) ipath_space (\<lambda>p. iglue T (fst p) (snd p))"

lemma sets_iextend[simp]:
  "sets (iextend T Q :: ('n::finite pairpath) measure) = sets ipath_space"
  unfolding iextend_def by simp

lemma iextend_measurable:
  fixes Q :: "('n::finite pairpath) measure"
  assumes T: "0 \<le> T"
    and setsQ: "sets Q = sets (path_borel T :: ('n pairpath) measure)"
  shows "(\<lambda>p. iglue T (fst p) (snd p)) \<in> Q \<Otimes>\<^sub>M ibm_law \<rightarrow>\<^sub>M ipath_space"
  by (rule iglue_measurable[OF T setsQ sets_ibm_law])

lemma prob_space_iextend:
  fixes Q :: "('n::finite pairpath) measure"
  assumes T: "0 \<le> T" and Q: "Q \<in> exit_class k L T x"
  shows "prob_space (iextend T Q)"
proof -
  interpret PQ: prob_space Q by (rule exit_class_prob[OF Q])
  interpret PR: prob_space "ibm_law :: ('n pairpath) measure"
    by (rule prob_space_ibm_law)
  interpret PP: prob_space "Q \<Otimes>\<^sub>M (ibm_law :: ('n pairpath) measure)"
    by (rule prob_space_pair_measure[OF PQ.prob_space_axioms
          PR.prob_space_axioms])
  show ?thesis
    unfolding iextend_def
    by (rule PP.prob_space_distr[OF iextend_measurable[OF T exit_class_sets[OF Q]]])
qed

text \<open>Cutting the extension at a horizon beyond the glue point returns the
  compact concatenation, so @{thm [source] exit_class_pglue_law} places every
  restriction of the extension in the class.\<close>

lemma pair_law_of_pcut_iextend:
  fixes Q :: "('n::finite pairpath) measure"
  assumes T: "0 \<le> T" and TS: "T \<le> S" and Q: "Q \<in> exit_class k L T x"
  shows "pair_law_of S (pcut S) (iextend T Q)
      = pglue_law T S Q (pair_law_of (S - T) (pcut (S - T)) ibm_law)"
proof -
  let ?B = "\<lambda>r. (path_borel r :: ('n pairpath) measure)"
  let ?R = "ibm_law :: ('n pairpath) measure"
  let ?g = "\<lambda>p :: 'n pairpath \<times> 'n pairpath. pglue T S (fst p) (snd p)"
  have S0: "0 \<le> S" using T TS by simp
  have ST0: "0 \<le> S - T" using TS by simp
  interpret PQ: prob_space Q by (rule exit_class_prob[OF Q])
  interpret PR: prob_space ?R by (rule prob_space_ibm_law)
  have setsQ: "sets Q = sets (?B T)" by (rule exit_class_sets[OF Q])
  have gm: "(\<lambda>p. iglue T (fst p) (snd p)) \<in> Q \<Otimes>\<^sub>M ?R \<rightarrow>\<^sub>M ipath_space"
    by (rule iextend_measurable[OF T setsQ])
  have cm: "pcut S \<in> (ipath_space :: ('n pairpath) measure) \<rightarrow>\<^sub>M ?B S"
    by (rule ipcut_measurable[OF S0 refl])
  have step1: "pair_law_of S (pcut S) (iextend T Q)
      = distr (Q \<Otimes>\<^sub>M ?R) (?B S) ?g"
  proof -
    have "pair_law_of S (pcut S) (iextend T Q)
        = distr (Q \<Otimes>\<^sub>M ?R) (?B S) (pcut S \<circ> (\<lambda>p. iglue T (fst p) (snd p)))"
      unfolding pair_law_of_def iextend_def by (rule distr_distr[OF cm gm])
    also have "\<dots> = distr (Q \<Otimes>\<^sub>M ?R) (?B S) ?g"
      by (simp add: comp_def pcut_iglue[OF S0])
    finally show ?thesis .
  qed
  have cutm: "pcut (S - T) \<in> ?R \<rightarrow>\<^sub>M ?B (S - T)"
    by (rule ipcut_measurable[OF ST0 sets_ibm_law])
  have sf: "sigma_finite_measure (distr ?R (?B (S - T)) (pcut (S - T)))"
    using PR.prob_space_distr[OF cutm]
    by (simp add: prob_space_imp_sigma_finite)
  have prodeq: "Q \<Otimes>\<^sub>M (pair_law_of (S - T) (pcut (S - T)) ?R)
      = distr (Q \<Otimes>\<^sub>M ?R) (?B T \<Otimes>\<^sub>M ?B (S - T))
          (\<lambda>p. (fst p, pcut (S - T) (snd p)))"
  proof -
    have "Q \<Otimes>\<^sub>M (pair_law_of (S - T) (pcut (S - T)) ?R)
        = distr Q (?B T) (\<lambda>u. u) \<Otimes>\<^sub>M distr ?R (?B (S - T)) (pcut (S - T))"
      unfolding pair_law_of_def by (simp add: distr_id2[OF setsQ[symmetric]])
    also have "\<dots> = distr (Q \<Otimes>\<^sub>M ?R) (?B T \<Otimes>\<^sub>M ?B (S - T))
        (\<lambda>(u, v). (u, pcut (S - T) v))"
      by (rule pair_measure_distr[OF measurable_ident_sets[OF setsQ] cutm sf])
    also have "\<dots> = distr (Q \<Otimes>\<^sub>M ?R) (?B T \<Otimes>\<^sub>M ?B (S - T))
        (\<lambda>p. (fst p, pcut (S - T) (snd p)))"
    proof -
      have "(\<lambda>(u, v). (u, pcut (S - T) v))
          = (\<lambda>p :: 'n pairpath \<times> 'n pairpath. (fst p, pcut (S - T) (snd p)))"
        by auto
      then show ?thesis by simp
    qed
    finally show ?thesis .
  qed
  have pgm: "?g \<in> ?B T \<Otimes>\<^sub>M ?B (S - T) \<rightarrow>\<^sub>M ?B S"
    by (rule pglue_measurable[OF T TS refl refl])
  have pairm: "(\<lambda>p :: 'n pairpath \<times> 'n pairpath. (fst p, pcut (S - T) (snd p)))
      \<in> Q \<Otimes>\<^sub>M ?R \<rightarrow>\<^sub>M ?B T \<Otimes>\<^sub>M ?B (S - T)"
    by (intro measurable_Pair measurable_compose[OF measurable_snd cutm]
        measurable_compose[OF measurable_fst measurable_ident_sets[OF setsQ]])
  have "pglue_law T S Q (pair_law_of (S - T) (pcut (S - T)) ?R)
      = distr (Q \<Otimes>\<^sub>M (pair_law_of (S - T) (pcut (S - T)) ?R)) (?B S) ?g"
    unfolding pglue_law_def pair_law_of_def ..
  also have "\<dots> = distr (Q \<Otimes>\<^sub>M ?R) (?B S)
      (?g \<circ> (\<lambda>p. (fst p, pcut (S - T) (snd p))))"
    unfolding prodeq by (rule distr_distr[OF pgm pairm])
  also have "\<dots> = distr (Q \<Otimes>\<^sub>M ?R) (?B S) ?g"
    by (simp add: comp_def pglue_pcut[OF T TS])
  finally show ?thesis unfolding step1 ..
qed

theorem iextend_cut_in_class:
  fixes Q :: "('n::finite pairpath) measure"
  assumes T: "0 \<le> T" and TS: "T \<le> S" and L: "1 \<le> L"
    and Q: "Q \<in> exit_class k L T x"
  shows "pair_law_of S (pcut S) (iextend T Q) \<in> exit_class k L S x"
proof -
  have ST0: "0 \<le> S - T" using TS by simp
  show ?thesis
    unfolding pair_law_of_pcut_iextend[OF T TS Q]
    by (rule exit_class_pglue_law[OF T TS Q ibm_law_cut_in_class[OF ST0 L]])
qed

text \<open>At the glue point itself the extension restricts to the law it
  extends: this is the identity the bridge asks for.\<close>

theorem pcut_law_iextend:
  fixes Q :: "('n::finite pairpath) measure"
  assumes T: "0 \<le> T" and Q: "Q \<in> exit_class k L T x"
  shows "pair_law_of T (pcut T) (iextend T Q) = Q"
proof -
  let ?B = "\<lambda>r. (path_borel r :: ('n pairpath) measure)"
  let ?R = "ibm_law :: ('n pairpath) measure"
  interpret PQ: prob_space Q by (rule exit_class_prob[OF Q])
  interpret PR: prob_space ?R by (rule prob_space_ibm_law)
  have setsQ: "sets Q = sets (?B T)" by (rule exit_class_sets[OF Q])
  have gm: "(\<lambda>p. iglue T (fst p) (snd p)) \<in> Q \<Otimes>\<^sub>M ?R \<rightarrow>\<^sub>M ipath_space"
    by (rule iextend_measurable[OF T setsQ])
  have cm: "pcut T \<in> (ipath_space :: ('n pairpath) measure) \<rightarrow>\<^sub>M ?B T"
    by (rule ipcut_measurable[OF T refl])
  have "pair_law_of T (pcut T) (iextend T Q)
      = distr (Q \<Otimes>\<^sub>M ?R) (?B T) (pcut T \<circ> (\<lambda>p. iglue T (fst p) (snd p)))"
    unfolding pair_law_of_def iextend_def by (rule distr_distr[OF cm gm])
  also have "\<dots> = distr (Q \<Otimes>\<^sub>M ?R) (?B T) (\<lambda>p. pcut T (fst p))"
    by (simp add: comp_def pcut_iglue[OF T] pglue_self)
  also have "\<dots> = distr (Q \<Otimes>\<^sub>M ?R) Q fst"
  proof (rule distr_cong[OF refl setsQ[symmetric]])
    fix p :: "'n pairpath \<times> 'n pairpath"
    assume "p \<in> space (Q \<Otimes>\<^sub>M ?R)"
    then have "fst p \<in> space Q" by (auto simp: space_pair_measure)
    then show "pcut T (fst p) = fst p"
      using space_of_path_sets[OF setsQ] by (simp add: pcut_id_on_mspace)
  qed
  also have "\<dots> = Q" by (rule PR.distr_pair_fst)
  finally show ?thesis .
qed

subsection \<open>Martingales from the restrictions\<close>

text \<open>Cutting at a horizon beyond \<open>u\<close> leaves the evaluations up to \<open>u\<close>
  untouched, so it identifies the two natural filtrations at \<open>u\<close>: every
  event of the half-line filtration is the preimage of an event of the
  horizon one.\<close>




lemma iextend_pcut_in_class:
  fixes Q :: "('n::finite pairpath) measure"
  assumes T: "0 \<le> T" and S: "0 \<le> S" and L: "1 \<le> L"
    and Q: "Q \<in> exit_class k L T x"
  shows "pair_law_of S (pcut S) (iextend T Q) \<in> exit_class k L S x"
proof (cases "T \<le> S")
  case True
  then show ?thesis by (rule iextend_cut_in_class[OF T _ L Q])
next
  case False
  let ?B = "\<lambda>r. (path_borel r :: ('n pairpath) measure)"
  have ST: "S \<le> T" using False by simp
  have "pair_law_of S (pcut S) Q
      = pair_law_of S (pcut S) (pair_law_of T (pcut T) (iextend T Q))"
    unfolding pcut_law_iextend[OF T Q] ..
  also have "\<dots> = distr (iextend T Q) (?B S) (pcut S \<circ> pcut T)"
    unfolding pair_law_of_def
    by (rule distr_distr[OF pcut_measurable[OF S ST refl]
          ipcut_measurable[OF T sets_iextend]])
  also have "\<dots> = pair_law_of S (pcut S) (iextend T Q)"
    unfolding pair_law_of_def by (simp add: comp_def pcut_pcut[OF ST])
  finally show ?thesis using exit_class_pcut[OF S ST Q] by simp
qed

theorem iextend_in_iexit_class:
  fixes Q :: "('n::finite pairpath) measure"
  assumes T: "0 \<le> T" and L: "1 \<le> L" and Q: "Q \<in> exit_class k L T x"
  shows "iextend T Q \<in> iexit_class k L x"
proof -
  let ?P = "iextend T Q"
  let ?G = "natural_filtration ?P 0 (\<lambda>v \<omega> :: 'n pairpath. \<omega> v)"
  have prob: "prob_space ?P" by (rule prob_space_iextend[OF T Q])
  have cutm: "pcut S \<in> ?P \<rightarrow>\<^sub>M (path_borel S :: ('n pairpath) measure)" if S: "0 \<le> S" for S
    by (rule ipcut_measurable[OF S sets_iextend])
  have cls: "pair_law_of S (pcut S) ?P \<in> exit_class k L S x" if S: "0 \<le> S" for S
    by (rule iextend_pcut_in_class[OF T S L Q])

  \<comment> \<open>clause (i): the initial condition\<close>
  have start: "AE \<omega> in ?P. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0"
  proof -
    have "AE \<omega> in pair_law_of T (pcut T) ?P. fst (\<omega> 0) = x \<and> snd (\<omega> 0) = 0"
      using cls[OF T] unfolding exit_class_def by blast
    then have "AE \<omega> in ?P. fst (pcut T \<omega> 0) = x \<and> snd (pcut T \<omega> 0) = 0"
      unfolding pair_law_of_def by (rule AE_distrD[OF cutm[OF T]])
    then show ?thesis using T by (simp add: pcut_def)
  qed

  \<comment> \<open>clause (ii): the covariation constraint, at every pair of times\<close>
  have dq: "AE \<omega> in ?P. \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow>
      (1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L"
  proof -
    have step: "AE \<omega> in ?P. \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow> t \<le> T + real n \<longrightarrow>
        (1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L" for n :: nat
    proof -
      have S: "0 \<le> T + real n" using T by simp
      have "AE \<omega> in pair_law_of (T + real n) (pcut (T + real n)) ?P.
          \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow> t \<le> T + real n \<longrightarrow>
            (1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L"
        using cls[OF S] unfolding exit_class_def by blast
      then have "AE \<omega> in ?P. \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow> t \<le> T + real n \<longrightarrow>
          (1 / (t - s)) *\<^sub>R (snd (pcut (T + real n) \<omega> t)
            - snd (pcut (T + real n) \<omega> s)) \<in> sconstraint k L"
        unfolding pair_law_of_def by (rule AE_distrD[OF cutm[OF S]])
      then show ?thesis by eventually_elim (auto simp: pcut_def)
    qed
    have "AE \<omega> in ?P. \<forall>n :: nat. \<forall>s t. 0 \<le> s \<longrightarrow> s < t \<longrightarrow> t \<le> T + real n \<longrightarrow>
        (1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L"
      using step by (subst AE_all_countable) blast
    then show ?thesis
    proof eventually_elim
      case (elim \<omega>)
      show ?case
      proof (intro allI impI)
        fix s t :: real assume st: "0 \<le> s" "s < t"
        obtain n :: nat where "t < real n" using reals_Archimedean2 by blast
        then have "t \<le> T + real n" using T by simp
        then show "(1 / (t - s)) *\<^sub>R (snd (\<omega> t) - snd (\<omega> s)) \<in> sconstraint k L"
          using elim st by blast
      qed
    qed
  qed

  \<comment> \<open>clause (iii): the coordinate process is a martingale\<close>
  have Xmg: "martingale ?P ?G 0 (\<lambda>u \<omega>. fst (\<omega> u) :: real^'n)"
  proof (rule martingale_of_cuts[OF prob sets_iextend])
    fix u :: real assume u: "0 \<le> u"
    have fstB: "(\<lambda>p :: (real^'n) \<times> (real^'n^'n). fst p) \<in> borel_measurable borel"
      by (intro borel_measurable_continuous_onI continuous_intros)
    have ev: "(\<lambda>\<omega> :: 'n pairpath. \<omega> u) \<in> ?G u \<rightarrow>\<^sub>M borel"
      unfolding natural_filtration_def
      by (rule measurable_family_vimage_algebra) (use u in auto)
    show "(\<lambda>\<omega> :: 'n pairpath. fst (\<omega> u)) \<in> borel_measurable (?G u)"
      by (rule measurable_compose[OF ev fstB])
  next
    fix u S :: real and \<omega> :: "'n pairpath"
    assume "0 \<le> u" "u \<le> S"
    then show "fst (pcut S \<omega> u) = fst (\<omega> u)" by (auto simp: pcut_def)
  next
    fix S :: real assume S: "0 \<le> S"
    show "martingale (pair_law_of S (pcut S) ?P)
        (natural_filtration (pair_law_of S (pcut S) ?P) 0 (\<lambda>v \<omega>. \<omega> v)) 0
        (\<lambda>u \<omega>. fst (\<omega> (min u S)) :: real^'n)"
      by (rule exit_class_X_martingale[OF cls[OF S]])
  qed

  \<comment> \<open>clause (iv): the compensated process is a martingale\<close>
  have Cmg: "martingale ?P ?G 0
      (\<lambda>u \<omega>. outerp (fst (\<omega> u) :: real^'n) - snd (\<omega> u))"
  proof (rule martingale_of_cuts[OF prob sets_iextend])
    fix u :: real assume u: "0 \<le> u"
    have e: "(\<lambda>p :: (real^'n) \<times> (real^'n^'n). outerp (fst p) - snd p)
        = (\<lambda>p. \<chi> i j. fst p $ i * fst p $ j - snd p $ i $ j)"
      by (rule ext) (simp add: outerp_def vec_eq_iff)
    have cB: "(\<lambda>p :: (real^'n) \<times> (real^'n^'n). outerp (fst p) - snd p)
        \<in> borel_measurable borel"
      unfolding e
      by (intro borel_measurable_continuous_onI continuous_on_vec_lambda
          continuous_intros)
    have ev: "(\<lambda>\<omega> :: 'n pairpath. \<omega> u) \<in> ?G u \<rightarrow>\<^sub>M borel"
      unfolding natural_filtration_def
      by (rule measurable_family_vimage_algebra) (use u in auto)
    show "(\<lambda>\<omega> :: 'n pairpath. outerp (fst (\<omega> u)) - snd (\<omega> u))
        \<in> borel_measurable (?G u)"
      by (rule measurable_compose[OF ev cB])
  next
    fix u S :: real and \<omega> :: "'n pairpath"
    assume "0 \<le> u" "u \<le> S"
    then show "outerp (fst (pcut S \<omega> u) :: real^'n) - snd (pcut S \<omega> u)
        = outerp (fst (\<omega> u)) - snd (\<omega> u)" by (auto simp: pcut_def)
  next
    fix S :: real assume S: "0 \<le> S"
    show "martingale (pair_law_of S (pcut S) ?P)
        (natural_filtration (pair_law_of S (pcut S) ?P) 0 (\<lambda>v \<omega>. \<omega> v)) 0
        (\<lambda>u \<omega>. outerp (fst (\<omega> (min u S)) :: real^'n) - snd (\<omega> (min u S)))"
      by (rule exit_class_compensated_martingale[OF cls[OF S]])
  qed

  show ?thesis
    unfolding iexit_class_def mem_Collect_eq
    using prob sets_iextend start dq Xmg Cmg by blast
qed

text \<open>The construction the bridge was reduced to: every member of the
  horizon-\<open>T\<close> class is the restriction of a member of the uncapped class.\<close>

theorem exit_class_has_extension:
  fixes Q :: "('n::finite pairpath) measure"
  assumes T: "0 \<le> T" and L: "1 \<le> L" and Q: "Q \<in> exit_class k L T x"
  shows "\<exists>P \<in> iexit_class k L x. pair_law_of T (pcut T) P = Q"
  using iextend_in_iexit_class[OF T L Q] pcut_law_iextend[OF T Q] by blast

subsection \<open>The two value functions, unconditionally\<close>

text \<open>With the construction in place, both hypotheses of
  @{thm [source] iexit_val_eq_of_extension} that were about the class are
  discharged, and only the paper's own standing assumptions remain.\<close>

theorem iexit_val_eq_exit_val:
  fixes K :: "(real^'n::finite) set"
  assumes T: "0 \<le> T" and L: "1 \<le> L" and Kc: "closed K"
    and nobind: "exit_val k L T K x < ennreal T"
  shows "iexit_val k L K x = exit_val k L T K x"
  by (rule iexit_val_eq_of_extension[OF T Kc nobind
        exit_class_has_extension[OF T L]])

text \<open>For a bounded \<open>K\<close> the a priori bound
  @{thm [source] exit_val_le_ball_bound} makes the remaining hypothesis a
  condition on the horizon alone, so the paper's value function of Eq. (1.6)
  is the capped one at every horizon past the scale \<open>(r\<^sup>2 - |x|\<^sup>2)/(n-k)\<close>.\<close>

corollary iexit_val_eq_exit_val_bounded:
  fixes K :: "(real^'n::finite) set" and r :: real
  assumes k: "k < CARD('n)" and L: "1 \<le> L" and T: "0 < T"
    and Kc: "closed K" and KB: "K \<subseteq> cball 0 r"
    and big: "(r * r - x \<bullet> x) / real (CARD('n) - k) < T"
  shows "iexit_val k L K x = exit_val k L T K x"
proof (rule iexit_val_eq_exit_val[OF less_imp_le[OF T] L Kc])
  have "exit_val k L T K x
      \<le> ennreal ((r * r - x \<bullet> x) / real (CARD('n) - k))"
    using L by (intro exit_val_le_ball_bound[OF k less_imp_le[OF T] _ KB]) simp
  also have "\<dots> < ennreal T" by (rule ennreal_lessI[OF T big])
  finally show "exit_val k L T K x < ennreal T" .
qed

text \<open>The bound is largest at the centre, so the hypothesis is uniform in
  \<open>x\<close>: one horizon beyond \<open>r\<^sup>2/(n-k)\<close> identifies the two value functions
  everywhere at once, which is what a clause quantified over points needs.\<close>

corollary iexit_val_eq_exit_val_ball:
  fixes K :: "(real^'n::finite) set" and rK :: real
  assumes k: "k < CARD('n)" and L: "1 \<le> L" and Kc: "closed K"
    and KB: "K \<subseteq> cball 0 rK"
    and big: "rK * rK / real (CARD('n) - k) < T"
  shows "iexit_val k L K x = exit_val k L T K x"
proof (rule iexit_val_eq_exit_val_bounded[OF k L _ Kc KB])
  have nk: "0 < real (CARD('n) - k)" using k by simp
  have sq: "0 \<le> rK * rK" by simp
  then have "0 \<le> rK * rK / real (CARD('n) - k)" using nk by simp
  then show "0 < T" using big by (rule order.strict_trans1)
  have "(rK * rK - x \<bullet> x) / real (CARD('n) - k)
      \<le> rK * rK / real (CARD('n) - k)"
    using nk by (intro divide_right_mono) auto
  then show "(rK * rK - x \<bullet> x) / real (CARD('n) - k) < T" using big by simp
qed

(*<*)
end
(*>*)
